{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "django-k8s-chart.serviceAccountName" . }}
  namespace: {{ .Values.serviceAccount.namespace}}
   
{{- end }}
