apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pv
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k8s-scs
  hostPath:
      path: "/mnt/data"
  # nfs:
  #   server: fs-0d1dd66c8b001d6c1.efs.eu-west-2.amazonaws.com
  #   path: /

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: k8s-scs
  resources:
    requests:
      storage: 3Gi
